security.jwt.token.secret-key: my-secret-key

spring:
  datasource:
    url: jdbc:postgresql://balarama.db.elephantsql.com/wklwobuw
    username: wklwobuw
    password: evBI9t3CmGU6311Cl6g4MuJsYVgeAftA
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
